import { Injectable } from '@angular/core';
import { InMemoryDbService, RequestInfo } from 'angular-in-memory-web-api';
import { Observable } from 'rxjs';
import { Category, Product } from './product/product';
import { User } from './user/user';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDbMartService implements InMemoryDbService {
  createDb(
    reqInfo?: RequestInfo | undefined
  ): {} | Observable<{}> | Promise<{}> {
    let products: Product[] = [
      {
        id: 1,
        name: 'Milk',
        price: 50,
        img: '../../../assets/images/milk.jpeg',
        category: Category.Dairy,
        rating: 3.7,
        quantity: 0,
      },
      {
        id: 2,
        name: 'Lipstick',
        price: 100,
        img: '../../../assets/images/lipstick.jpeg',
        category: Category.Beauty,
        rating: 2,
        quantity: 0,
      },
      {
        id: 3,
        name: 'Mobile',
        price: 5000,
        img: '../../../assets/images/mobile.jpeg',
        category: Category.Tech,
        rating: 3,
        quantity: 0,
      },
      {
        id: 4,
        name: 'Biscuit',
        price: 50,
        img: '../../../assets/images/biscuit.jpeg',
        category: Category.Grocery,
        rating: 1.7,
        quantity: 0,
      },
      {
        id: 5,
        name: 'Curd',
        price: 20,
        img: '../../../assets/images/curd.jpeg',
        category: Category.Dairy,
        rating: 4.2,
        quantity: 0,
      },
      {
        id: 6,
        name: 'Maggie',
        price: 24,
        img: '../../../assets/images/pasta.jpeg',
        category: Category.Grocery,
        rating: 3,
        quantity: 0,
      },
      {
        id: 7,
        name: 'Airpod',
        price: 2040,
        img: '../../../assets/images/airpod.jpeg',
        category: Category.Tech,
        rating: 4,
        quantity: 0,
      },
      {
        id: 8,
        name: 'Apple',
        price: 50,
        img: '../../../assets/images/apple.jpeg',
        category: Category.Fruits,
        rating: 4.7,
        quantity: 0,
      },
      {
        id: 9,
        name: 'Banana',
        price: 60,
        img: '../../../assets/images/banana.jpeg',
        category: Category.Fruits,
        rating: 3,
        quantity: 0,
      },
      {
        id: 10,
        name: 'Bed',
        price: 50000,
        img: '../../../assets/images/bed.jpeg',
        category: Category.Furniture,
        rating: 3,
        quantity: 0,
      },
      {
        id: 11,
        name: 'Boots',
        price: 5000,
        img: '../../../assets/images/boot.jpeg',
        category: Category.Footwear,
        rating: 5,
        quantity: 0,
      },
      {
        id: 12,
        name: 'Bread',
        price: 30,
        img: '../../../assets/images/bread.jpeg',
        category: Category.Grocery,
        rating: 4,
        quantity: 0,
      },
      {
        id: 13,
        name: 'Butter',
        price: 15,
        img: '../../../assets/images/butter.jpeg',
        category: Category.Dairy,
        rating: 3,
        quantity: 0,
      },
      {
        id: 14,
        name: 'Cabinet',
        price: 20000,
        img: '../../../assets/images/cab.jpeg',
        category: Category.Furniture,
        rating: 2,
        quantity: 0,
      },
      {
        id: 15,
        name: 'Winter Cap',
        price: 24,
        img: '../../../assets/images/cap.jpeg',
        category: Category.Clothing,
        rating: 1,
        quantity: 0,
      },
      {
        id: 16,
        name: 'Chair',
        price: 700,
        img: '../../../assets/images/chair.jpeg',
        category: Category.Furniture,
        rating: 4,
        quantity: 0,
      },
      {
        id: 17,
        name: 'Cheese',
        price: 40,
        img: '../../../assets/images/cheese.jpeg',
        category: Category.Dairy,
        rating: 3,
        quantity: 0,
      },
      {
        id: 18,
        name: 'Coffee',
        price: 20,
        img: '../../../assets/images/coffee.jpeg',
        category: Category.Grocery,
        rating: 3,
        quantity: 0,
      },
      {
        id: 19,
        name: 'Cream',
        price: 900,
        img: '../../../assets/images/cream.jpeg',
        category: Category.Beauty,
        rating: 3,
        quantity: 0,
      },
      {
        id: 20,
        name: 'Crocs',
        price: 4999,
        img: '../../../assets/images/crocs.jpeg',
        category: Category.Footwear,
        rating: 4,
        quantity: 0,
      },
      {
        id: 21,
        name: 'Curd',
        price: 20,
        img: '../../../assets/images/curd.jpeg',
        category: Category.Dairy,
        rating: 3,
        quantity: 0,
      },
      {
        id: 22,
        name: 'Custard',
        price: 55,
        img: '../../../assets/images/custard.jpeg',
        category: Category.Dairy,
        rating: 3,
        quantity: 0,
      },
      {
        id: 23,
        name: 'Cold Drink',
        price: 20,
        img: '../../../assets/images/drink.jpeg',
        category: Category.Grocery,
        rating: 3,
        quantity: 0,
      },
      {
        id: 24,
        name: 'Anar',
        price: 70,
        img: '../../../assets/images/pomo.jpeg',
        category: Category.Fruits,
        rating: 3,
        quantity: 0,
      },
      {
        id: 25,
        name: 'Garlic',
        price: 10,
        img: '../../../assets/images/garlic.jpeg',
        category: Category.Veges,
        rating: 3,
        quantity: 0,
      },
      {
        id: 26,
        name: 'Tomato',
        price: 40,
        img: '../../../assets/images/tomato.jpeg',
        category: Category.Veges,
        rating: 3,
        quantity: 0,
      },
      {
        id: 27,
        name: 'Tablet',
        price: 65000,
        img: '../../../assets/images/tablet.jpeg',
        category: Category.Tech,
        rating: 3,
        quantity: 0,
      },
      {
        id: 28,
        name: 'Smart Watch',
        price: 10000,
        img: '../../../assets/images/watch.jpeg',
        category: Category.Tech,
        rating: 3,
        quantity: 0,
      },
      {
        id: 29,
        name: 'Electric Kettle',
        price: 5000,
        img: '../../../assets/images/kettle.jpeg',
        category: Category.Appliances,
        rating: 3,
        quantity: 0,
      },
      {
        id: 30,
        name: 'Toaster',
        price: 7000,
        img: '../../../assets/images/toast.jpeg',
        category: Category.Appliances,
        rating: 3,
        quantity: 0,
      },
      {
        id: 31,
        name: 'Shirt',
        price: 1999,
        img: '../../../assets/images/tshirt.jpeg',
        category: Category.Clothing,
        rating: 3,
        quantity: 0,
      },
      {
        id: 32,
        name: 'Jeans',
        price: 2999,
        img: '../../../assets/images/jean.jpeg',
        category: Category.Clothing,
        rating: 3,
        quantity: 0,
      },
      {
        id: 33,
        name: 'Mascara',
        price: 900,
        img: '../../../assets/images/mascara.jpeg',
        category: Category.Beauty,
        rating: 3,
        quantity: 0,
      },
    ];

    let users: User[] = [
      { id: 1, userName: 'Vatsal', isAdmin: true, password: 'vatsal' },
      { id: 2, userName: 'Anish', isAdmin: false, password: 'vatsal' },
      { id: 3, userName: 'Ayush', isAdmin: false, password: 'vatsal' },
      { id: 4, userName: 'Vedic', isAdmin: false, password: 'vatsal' },
    ];
    return { products, users };
  }
}
